name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        node: ['14.x', '16.x']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: npm i -g pnpm@6.20.3
    - run: pnpm install --frozen-lockfile
    - run: yarn lint
    - run: yarn build
    - run: yarn test
  test-example:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm i -g pnpm@6.20.3
      - run: pnpm install --frozen-lockfile
      - name: Build core
        run: yarn build
        working-directory: packages/core
      - name: Build coingecko
        run: yarn build
        working-directory: packages/coingecko
      - name: Run playwright
        run: |
          set -e
          yarn start &
          xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- yarn test:playwright
        env:
          MAINNET_URL: ${{ secrets.MAINNET_PROVIDER_URL }}
          DEBUG: usedapp*
        working-directory: packages/example
  test-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm i -g pnpm@6.20.3
      - run: pnpm install --frozen-lockfile
      - name: Build core
        run: yarn build
        working-directory: packages/core
      - name: Build coingecko
        run: yarn build
        working-directory: packages/coingecko
      - name: Run playwright
        run: |
          set -e
          yarn start &
          xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- yarn test:playwright
        env:
          MAINNET_URL: ${{ secrets.MAINNET_PROVIDER_URL }}
          DEBUG: usedapp*
        working-directory: packages/docs
